api/urls.py
from django.urls import path
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

from egs.settings import *
from egs import settings
from .views import *

urlpatterns = [
     path('', get_devices, name='devices'),
     path('device/<int:id_dev>', get_device, name='device'),
]

core/urls.py
from django.urls import path
from django.urls import re_path
from django.conf.urls.static import static
from django.views.static import serve

from egs.settings import *
from egs import settings
from .views import *

urlpatterns = [
     path('task/<int:id>/', get_task_by_id, name='task'),
     path('', home, name='home'),
     path('login/', loginPage, name='login'),
     path('docs/', show_docs, name='show_docs'),
     path('mails/<int:id>', mails, name='mails'),
     path('mails/show/<int:id>/<int:my_type>', get_mail_by_id, name='get_mail_by_id'),
     path('mails/show/edit/<int:id>/<int:my_type>', employee_mail, name='employee_mail'),
     path('mails/edit/<int:id>/<int:my_type>', mail_edit, name='mail_edit'),
     path('docs/comp_edit/<int:id_doc>', docs_edit, name='comp_edit'),
     path('docs/comp_edit/del/<int:id_doc>', docs_del, name='comp_del'),
     path('divisions/', divisions, name='divisions'),
     path('divisions/del/<int:id>', division_del, name='divisions_del'),
     path('employees/', employees, name='employees'),
     path('employees/edit/<int:id>', employee_edit, name='employee_edit'),
     path('employees/add/', employee_add, name='employee_add'),
     path('employees/edit/document/<int:id_doc>/<int:id_emp>', document_edit_employee, name='document_edit_employee'),
     path('employees/edit/document/delete/<int:id_doc>/<int:id_emp>', document_del_employee, name='document_del_employee'),
     path('objects/<int:id>', objects, name='objects'),
     path('objects/delete/<int:id>', object_del, name='object_del'),
     path('objects/tasks/<int:id>', show_tasks, name='show_tasks'),
     path('objects/edit/<int:id>', object_edit, name='card'),
     path('task/edit/<int:proj_id>/<int:id>', task_edit, name='card_task'),
     path('objects/edit/employee_project/<int:id>', employee_project, name='employee_project'),
     path('task/edit/employee_task/<int:id>', employee_task, name='employee_task'),
     path('task/edit/close_task/<int:id>', close_task, name='close_task'),
     path('objects/edit/document/<int:id_doc>/<int:id_proj>', document_edit, name='document_edit'),
     path('objects/edit/document/delete/<int:id_doc>/<int:id_proj>', document_del, name='document_del'),
     path('register/', register, name='register'),
     path('logout/', logoutUser, name='logout'),
     path('forgot-password/', forgot_password, name='forgot_password'),
     path('create-notification/', create_notification, name='create_notification'),
     path('notifications/mark-read/<int:notification_id>/', mark_notification_as_read, name='mark_notification_as_read'),
     path('notifications/mark-postponed/<int:notification_id>/', mark_notification_as_postponed,
          name='mark_notification_as_postponed'),
]

egs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings
from .settings import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('api/', include('api.urls')),
    re_path(r'^download/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns+=static(MEDIA_URL, document_root=MEDIA_ROOT)
    urlpatterns+=static(STATIC_URL, document_root=STATIC_ROOT)

core/models.py
from django.db import models
from django.conf import settings
import datetime
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

# Create your models here.

from django.db.models import QuerySet
from django.db.models.signals import post_save

from egs.managers import UserManager
from django.dispatch import receiver
import requests
from egs.settings import BOT_URL
from bot.models import TelegramUsers


#Class for Employees
class Employees(AbstractBaseUser, PermissionsMixin):

    #Basic user info
    email = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=63, verbose_name='Имя')
    surname = models.CharField(max_length=63, verbose_name='Фамилия')
    last_name = models.CharField(max_length=63, blank=True, null=True, verbose_name='Отчество')

    #Some more specific data
    phone = models.CharField(max_length=255, blank=True, null=True, verbose_name='Телефон')
    address = models.CharField(max_length=255, blank=True, null=True, verbose_name='Адрес')
    date_of_birth = models.DateField(verbose_name='Дата рождения', null=True)
    date_of_start = models.DateField(verbose_name='Дата начала', blank=True, null=True)
    inn = models.CharField(max_length=256, blank=True, null=True, verbose_name='ИНН')
    snils = models.CharField(max_length=256, blank=True, null=True, verbose_name='СНИЛС')
    passport = models.TextField(max_length=256, blank=True, null=True, verbose_name='Паспорт')
    post = models.CharField(max_length=255, blank=True, null=True, verbose_name='Должность')
    info_about_relocate = models.TextField(max_length=511, blank=True, null=True, verbose_name='Информация о переводе')
    attestation = models.CharField(max_length=255, blank=True, null=True, verbose_name='Аттестация')
    qualification = models.CharField(max_length=255, blank=True, null=True, verbose_name='Повышение квалификации')
    retraining = models.CharField(max_length=255, blank=True, null=True, verbose_name='Проф. подготовка')
    status = models.BooleanField(verbose_name='Статус', default=True)
    is_staff = models.BooleanField(verbose_name='Админ', default=False)
    is_active = models.BooleanField('active', default=True)
    # is_admin = models.BooleanField(default=False)
    ROLE_IN_SYSTEM_CHOICES = [
        ('DI', 'Директор'),
        ('ME', 'Менеджер/Инженер'),
        ('RA', 'Работник'),
        ('BU', 'Бухгалтер'),
        ('RN', 'Руководитель направления'),
        ('KS', 'Кадровый специалист')
    ]
    role = models.CharField(max_length=3,
                            choices=ROLE_IN_SYSTEM_CHOICES,
                            default='RA',
                            verbose_name='Роль',
                            blank=True)


    #Some company data
    COMPANY_CHOICES = [
        ('GP', 'ГАЗСПЕЦПРОЕКТ'),
        ('NG', 'Не ГАЗСПЕЦПРОЕКТ')
    ]
    company = models.CharField(max_length=3,
                               choices=COMPANY_CHOICES,
                               default='GP',
                               verbose_name='Компания',
                               blank=True)
    DIVISION_CHOICES = [
        ('GSP', 'ГАЗСПЕЦПРОЕКТ'),
        ('PTO', 'Производственно-технический отдел (ПТО)'),
        ('WGP', 'Водгазпроект')
    ]
    division = models.ForeignKey(
        "Divisions",
        on_delete=models.deletion.PROTECT,
        related_name="employee_to_div",
        null=True,
        blank=True,
        verbose_name='Подразделение'
    )
    leader = models.ForeignKey(
        "self",
        on_delete=models.deletion.CASCADE,
        null=True,
        blank=True,
        verbose_name='Начальник'
    )

    #Some many to many fields and functions
    employee_to_task = models.ManyToManyField(
        "Tasks",
        related_name="employees",
        blank=True,
        verbose_name='Задания'
    )
    employee_to_project = models.ManyToManyField(
        "Projects",
        related_name="projects",
        blank=True,
        verbose_name='Объекты'
    )

    employee_to_document = models.ManyToManyField(
        "Documents",
        related_name="employee_to_doc",
        blank=True,
        verbose_name='Документы'
    )

    employee_to_mail = models.ManyToManyField(
        "Mails",
        related_name="employee_to_mail",
        blank=True,
        verbose_name='Письма'
    )

    @property
    def mails(self) -> QuerySet['Mails']:
        return Mails.objects.filter(employees_to_mails__name=self.name)

    def get_role(self):

        if self.role == 'DI':
            return 'Директор'
        if self.role == 'ME':
            return 'Менеджер/Инженер'
        if self.role == 'RA':
            return 'Работник'
        if self.role == 'BU':
            return 'Бухгалтер'
        if self.role == 'RN':
            return 'Руководитель направления'
        if self.role == 'KS':
            return 'Кадровый специалист'

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    def __str__(self):
        return str(self.surname + ' ' + self.name)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


@receiver(post_save, sender=Employees)
def call_emp(sender, instance, **kwargs):
    CompanyDocuments.objects.update_or_create(pk=1)



class Messages(models.Model):
    message = models.TextField(max_length=1024, verbose_name='Сообщение')
    author = models.ForeignKey(
        "Employees",
        on_delete=models.deletion.PROTECT,
        verbose_name='Автор'
    )
    task = models.ForeignKey(
        "Tasks",
        on_delete=models.deletion.PROTECT,
        related_name="messages",
        verbose_name='Задание',
        null=True
    )
    mails_tag = models.ForeignKey(
        "Mails",
        on_delete=models.deletion.PROTECT,
        related_name="messages_to_mails",
        verbose_name='Письмо',
        null=True
    )

    time = models.DateTimeField(auto_now=True)

    doc = models.FileField(null=True, blank=True, upload_to='upload_messages', verbose_name='Документ')

    def __str__(self):
        return self.message

    def has_file(self):
        return bool(self.doc)

    class Meta:
        verbose_name = 'Сообщения'
        verbose_name_plural = 'Сообщения'


@receiver(post_save, sender=Messages)
def call_message(sender, instance, **kwargs):
    users = None
    my_object = None
    message_type = None
    try:
        users = instance.task.employees.all()
        my_object = instance.task
        message_type = 'ОБЪЕКТУ'
    except:
        users = instance.mails_tag.employees.all()
        my_object = instance.mails_tag
        message_type = 'ПИСЬМУ'

    print(users)
    print(my_object)
    for user in users:
        bot_user = None
        print(user)
        try:
            bot_user = TelegramUsers.objects.get(phone_number=user.phone)
        except:
            pass
        # print(bot_user.phone_number)
        if bot_user:
            chat_id = bot_user.chat_id

            message = f'*Тип*:   СООБЩЕНИЕ ПО {message_type} *{my_object}*🔔\n\n*От*: {instance.author}\n\n*Текст сообщения*💬:\n    {instance.message}'

            requests.post(BOT_URL + 'sendMessage', json={'chat_id': int(chat_id), 'text': message, 'parse_mode': 'Markdown'})



class Tasks(models.Model):
    name = models.CharField(max_length=1023, verbose_name='Задание', blank=True)
    author = models.ForeignKey(
        "Employees",
        on_delete=models.deletion.CASCADE,
        verbose_name='Автор'
    )
    created = models.DateField(verbose_name='Дата создания')
    completion = models.DateField(verbose_name='Срок выполнения')
    done = models.DateTimeField(verbose_name='Дата выполнения', null=True, blank=True)
    projects = models.ForeignKey(
        "Projects",
        on_delete=models.deletion.PROTECT,
        related_name="tasks",
        verbose_name='Проект'
    )

    @property
    def messages(self) -> QuerySet[Messages]:
        return Messages.objects.filter(task__name=self.name).order_by('-author__date_of_birth')

    @property
    def employees(self) -> QuerySet[Employees]:
        return Employees.objects.filter(employee_to_task__name=self.name)

    @property
    def get_type(self):
        if self.done:
            return 0
        if self.projects.proj_type == 'EXP':
            if self.completion >= datetime.date.today():
                return 1
            else:
                return 2

        if self.projects.proj_type == 'TO':
            if self.completion >= datetime.date.today():
                return 3
            else:
                return 4

        if self.projects.proj_type == 'SMR':
            if self.completion >= datetime.date.today():
                return 5
            else:
                return 6

        if self.projects.proj_type == 'PRO':
            if self.completion >= datetime.date.today():
                return 7
            else:
                return 8

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Задачи'
        verbose_name_plural = 'Задачи'



class Mails(models.Model):
    name = models.CharField(max_length=1023, verbose_name='Описание')
    naming = models.CharField(max_length=1023, verbose_name='Наименование отправителя/получателя')
    created = models.DateField(verbose_name='Дата создания', auto_now=True)
    date_reg = models.DateField(verbose_name='Дата регистрации')
    number = models.CharField(max_length=1023, verbose_name='Номер')
    author = models.ForeignKey(
        "Employees",
        on_delete=models.deletion.CASCADE,
        verbose_name='Автор'
    )
    completion = models.DateField(verbose_name='Срок выполнения', null=True, blank=True)
    done = models.DateField(verbose_name='Дата выполнения', null=True, blank=True)
    type = models.CharField(max_length=256, verbose_name='Тип')
    projects_to_mails = models.ForeignKey(
        "Projects",
        on_delete=models.deletion.CASCADE,

core/templates/core/documents.html
{% extends 'core/base.html' %}

{% block content %}
    <!-- Document card-->
        <div class="col-xl-12 col-md-6 mb-4">

            <div class="card shadow h-100 py-2">
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="col-sm-12">
                            <div class="card-box">
                                <div class="h4 mb-4 font-weight-bold text-gray-800">Документация</div>
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Название документа</th>
                                        <th>Тип договора</th>
                                        <th>Статус</th>
                                        <th>Срок действия</th>
                                        <th>Ссылка</th>
                                        <th>Удалить</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>ID</th>
                                        <th>Название документа</th>
                                        <th>Тип договора</th>
                                        <th>Статус</th>
                                        <th>Срок действия</th>
                                        <th>Ссылка</th>
                                        <th>Удалить</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for document in docs %}
                                        <tr>
                                            <td>
                                                <a class="btn btn-primary btn-sm"
                                                   href="{% url 'comp_edit' id_doc=document.id %}">
                                                {{ document.id }}
                                                </a>
                                            </td>
                                            <td>{{ document.name }}</td>
                                            <td>{{ document.get_doc_type_display }}</td>
                                            <td>{{ document.get_status_display }}</td>
                                            <td>{{ document.duration.isoformat }}</td>
                                            <td>
                                                {% if document.doc %}
                                                    <a class="btn btn-primary btn-sm" href="{{ document.doc.url }}" download="{{ document.doc.url }}">
                                                        Скачать
                                                    </a>
                                                {% else %}
                                                    <button class="btn btn-primary btn-sm">
                                                        Нет файла
                                                    </button>
                                                {% endif %}
                                            </td>
                                            <td>
                                                <a class="btn btn-danger btn-sm"
                                                   href="{% url 'comp_del' id_doc=document.id%}">
                                                Удалить
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="m-t-20">
                                <a href="{% url 'comp_edit' id_doc=0%}"
                                   class="btn btn-success waves-effect waves-light m-l-10 btn-md">+Добавить документ
                                </a>
                            </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

core/templates/core/employees.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Сотрудники</h1>
    <p class="mb-4">Сотрудники</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Сотрудники</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ФИО</th>
                            <th>Роль</th>
                            <th>Телефон</th>
                            <th>E-Mail</th>
                            <th>Должность</th>
                            <th>Статус</th>
                            <th>Свойства</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ФИО</th>
                            <th>Роль</th>
                            <th>Телефон</th>
                            <th>E-Mail</th>
                            <th>Должность</th>
                            <th>Статус</th>
                            <th>Свойства</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    {% for employee in employees %}
                        <tr>
                            <td>{{ employee }}</td>
                            <td>{{ employee.get_role_display }}</td>
                            <td>{{ employee.phone }}</td>
                            <td>{{ employee.email }}</td>
                            <td>{{ employee.post }}</td>
                            {% if employee.status %}
                                <td><label class="btn btn-success btn-sm">Активен</label></td>
                            {% else %}
                                <td><label class="btn btn-secondary btn-sm">Заблокирован</label></td>
                            {% endif %}
                            <td><a href="{% url 'employee_edit' id=employee.id %}" class="btn btn-primary btn-sm">Открыть</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            <div class="m-t-20">
                <a href="{% url 'employee_add' %}"
                   class="btn btn-success waves-effect waves-light m-l-10 btn-md">
                    +Добавить пользователя
                </a>
            </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

core/templates/core/mail_edit.html
{% extends 'core/base.html' %}

{% block content %}
    <!-- Base container-->
    <div class="container-fluid">

        <!-- Card header-->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="h5 mb-0 font-weight-bold text-gray-800">Карточка письма</div>
                </div>
            </div>
        </div>

        <!-- Object editor card-->
        <div class="col-xl-12 col-md-6 mb-4">

            <div class="card shadow h-100 py-2">
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="POST">
                        {% csrf_token %}
                        <div class="col-sm-12">
                            <div class="card-box">
                                <div class="h4 mb-0 font-weight-bold text-gray-800">{{ mail.name }}</div>
                                <p class="text-muted m-b-30 font-13">Редактирование письма</p>


                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="col-md-4 font-weight-bold control-label">Название</label>
                                            <div class="col-md-8">
                                                {{ form.name }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-4 font-weight-bold control-label">Наименование отправителя/получателя</label>
                                            <div class="col-md-8">
                                                <div class="input-group">
                                                    {{ form.naming }}
                                                    <span class="input-group-addon bg-primary b-0 text-white"><i
                                                            class="icon-calender"></i></span>
                                                </div><!-- input-group -->
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-4 font-weight-bold control-label">Дата регистрации</label>
                                            <div class="col-md-8">
                                                <div class="input-group">
                                                    {{ form.date_reg }}
                                                    <span class="input-group-addon bg-primary b-0 text-white"><i
                                                            class="icon-calender"></i></span>
                                                </div><!-- input-group -->
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-4 font-weight-bold control-label">Номер</label>
                                            <div class="col-md-8">
                                                <div class="input-group">
                                                    {{ form.number }}
                                                    <span class="input-group-addon bg-primary b-0 text-white"><i
                                                            class="icon-calender"></i></span>
                                                </div><!-- input-group -->
                                            </div>
                                        </div>


                                    </div>


                                </div>


                                <div class="m-t-20">
                                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10 btn-md"
                                            name="isSaved" value="1">Сохранить
                                    </button>
                                </div>

                            </div>
                        </div>
                    </form>
                    {{ form.errors }}
                </div>
            </div>
        </div>

        <div class="col-xl-12 col-md-6 mb-4">
            <div class="card shadow h-100 py-2">
                <div class="card-body">
                    <form class="form-horizontal" role="form" method="POST">
                        {% csrf_token %}
                        <div class="col-sm-12">
                            <div class="card-box">
                                <div class="h4 mb-4 font-weight-bold text-gray-800">Ответственные лица</div>

                                <table id="datatable" class="table table-bordered">
                                    <thead>
                                    </thead>
                                    <tbody>
                                    {% for emp in mail.employees %}
                                        <tr>
                                            <td>{{ emp }}<small>({{ emp.get_role }})</small></td>
                                            {% if request.user.is_superuser %}
                                                <td width="80">
                                                    <button type="submit" name="isSaved" value="{{ emp.id }}"
                                                            class="btn btn-danger btn-sm">
                                                        Удалить
                                                    </button>
                                                </td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                {% if request.user.is_superuser %}
                                    <select name="worker" class="form-control mb-3" id="id_status">
                                        <option selected hidden>Добавить сотрудника</option>
                                        {% for employee in employees %}
                                            <option value="{{ employee.id }}">{{ employee }}({{ employee.get_role }})</option>
                                        {% endfor %}
                                    </select>
                                    <div class="m-t-20">
                                        <button type="submit"
                                                class="btn btn-success waves-effect waves-light m-l-10 btn-md"
                                                name="isSaved" value="-1">Добавить
                                        </button>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/mails.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Письма</h1>
        <p class="mb-4">{{ type }}</p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Письма</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Описание</th>
                            <th>Отправитель</th>
                            <th>Дата письма</th>
                            <th>Дата регистрации</th>
                            <th>Номер</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Описание</th>
                            <th>Отправитель</th>
                            <th>Дата письма</th>
                            <th>Дата регистрации</th>
                            <th>Номер</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for mail in mails %}
                            {% if ttype == mail.type%}
                                <tr>
                                    <td><a color="#1cc88a" class="btn btn-primary btn-sm"
                                           href="{% url 'get_mail_by_id' id=mail.id my_type=type_id%}"
                                           class="label label-table label-success ">{{ mail.id }}</a></td>
                                    <td>{{ mail.name }}</td>
                                    <td>{{ mail.naming }}</td>
                                    <td>{{ mail.created }}</td>
                                    <td>{{ mail.date_reg }}</td>
                                    <td>{{ object.number }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if request.user.is_superuser %}
                        <div class="m-t-20">
                            <a href="{% url 'mail_edit' id=0 my_type=type_id%}">
                                <button type="submit" class="btn btn-success waves-effect waves-light m-l-10 btn-md"
                                        name="isSaved" value="1">+Добавить письмо
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}